### ISSUE TITLE
Node.js developer workflow

### ISSUE THREAD

**Issue by ruffle1986** [nodebp/nodebp#12]
How to develop and maintain large-scale applications written in Node.js? What are those important or useful steps that every node developer's workflow should consist of?
- What are the most common tasks during development (For example: releasing, testing, etc. by Grunt) ?
- How to organise code?
- How to share scripts between back-end and front-end side (For instance: path finding algorithm of an mmorp)?
- How to test performance in a proper way?
- and so on...

I'd be glad to hear about these things. :)

**Comment by oroce** [comment]
We will cover some of those steps in the package.json talk (see #4).

**Comment by ruffle1986** [comment]
nice! :)

**Comment by sonicoder86** [comment]
+1, code sharing can make a whole presentation by itself: #26
