### ISSUE TITLE
Desktop Application development with Node.js and node-webkit

### ISSUE THREAD

**Issue by necccc** [nodebp/nodebp#14]
Quick introduction to node-webkit with a small utility application to remote-debug the Ustream embed player.

This light talk would include topics such as:
- development, 
- running, 
- building with grunt

**Comment by gergelyke** [comment]
Would it be a deep dive, or basics?

**Comment by gergelyke** [comment]
Presentation at: https://github.com/nodebp/nodebp/blob/gh-pages/2014-Jan.md#3--building-desktop-applications-with-nodejs--by-szabolcs-toth
