### ISSUE TITLE
Hello node.js, aka NodeWHAT?

### ISSUE THREAD

**Issue by gergelyke** [nodebp/nodebp#2]
Short intro about Node.js, biggest companies who uses it: PayPal in details, they just introduced  it.
Then the main characteristics of Node, including callbacks, nonblocking I/O, etc...
Few lines of live coding, just to point out error-first callback styles, package.json and npm.
Mention nodeschool.io at the end.

**Comment by oroce** [comment]
accepted.

added milestone.

**Comment by oroce** [comment]
added to the readme: [link](https://github.com/nodebp/nodebp/blob/master/2013-Nov.md#1-nodewhat---javascript-szerveren-modulok-webszerver-package-management-by-gergely-n%C3%A9meth)
