### ISSUE TITLE
Node.js with Tmux

### ISSUE THREAD

**Issue by judikdavid** [nodebp/nodebp#23]
Talk about how to setup and use Tmux and vim with Node.js and solve a following issues:
- re-open the same tabs with the same commands (vim, node server, mongo, mongod) every day
- don't switch back and forth between your editor and node server, tests all the time
- use tmux for pair programming

**Comment by gergelyke** [comment]
:+1:

**Comment by oroce** [comment]
:+1:

**Comment by madbence** [comment]
Great idea, I love `vim` & `tmux` too! :+1:
