### ISSUE TITLE
Koa

### ISSUE THREAD

**Issue by gergelyke** [nodebp/nodebp#25]
```
console.log('thinking....')
```

**Comment by gergelyke** [comment]
If we have no other talk proposals for May, I could do this.
- what is --harmony
- short reminder of what generators are
- comparison with Express
- setting up a basic Koa app (not a demo, rather what to use/demo, but recorded and played)

What do you think?

**Comment by oroce** [comment]
Do you have any experience with Koa? Maybe some production experience?

**Comment by gergelyke** [comment]
Currently building APIs with it - if you mean in production with huge traffic, then no
