### ISSUE TITLE
Isomorph Javascript

### ISSUE THREAD

**Issue by sonicoder86** [nodebp/nodebp#26]
Presentation about how to share code between the browser and the server
Example application is a multiplayer minesweeper game.
https://github.com/blacksonic/minesweeper

**Comment by gergelyke** [comment]
Have you tried browserify?

**Comment by sonicoder86** [comment]
tried it also, but requirejs came first

**Comment by sonicoder86** [comment]
it is also covered in the talk, alternative solutions

**Comment by hekike** [comment]
@blacksonic +1

**Comment by gergelyke** [comment]
Sounds good - nodebp is on holiday, but could you give this talk in September?

**Comment by sonicoder86** [comment]
i can do it in September, till then ill have time digging more into other solutions also

**Comment by gergelyke** [comment]
Hey,
still up for doing it in Sept?

**Comment by sonicoder86** [comment]
On which day?

**Comment by gergelyke** [comment]
Were thinking about 24th, Sept.

**Comment by sonicoder86** [comment]
sounds good

**Comment by gergelyke** [comment]
http://www.meetup.com/nodebp/events/200263902/
