### ISSUE TITLE
Mocking

### ISSUE THREAD

**Issue by EggDice** [nodebp/nodebp#28]
Mocking, and TDD

stubs, fakes, dummies and mocks
how to do it in node
classic TDD vs. mockist TDD

I would be happy to do it after summer!

**Comment by gergelyke** [comment]
Must have ;)

Also, would be fun to have a meetup dedicated to testing and have a counter argument like: https://www.youtube.com/watch?v=z9quxZsLcfo

**Comment by EggDice** [comment]
Yeah that is where the idea came from, and Fowler's articles.

**Comment by EggDice** [comment]
Also compare testing frameworks:
qnuit, jasmine, mocha, tap, tape, jest

**Comment by gergelyke** [comment]
Hey,
how about doing it in September?

**Comment by EggDice** [comment]
I guess I should! :P

**Comment by gergelyke** [comment]
http://www.meetup.com/nodebp/events/200263902/
