### ISSUE TITLE
AsyncListeners

### ISSUE THREAD

**Issue by madbence** [nodebp/nodebp#29]
`AsyncListeners` will be available in node v0.12 (and they are available right now in the unstable branch), they are maybe the most interesting feature in the next version. Preso about:
- How to keep execution context in asynchronous code
- Available tools (long stacktrace, continuation-localstorage)
- Available polyfills in v0.10
- Performance

**Comment by gergelyke** [comment]
WANT!

**Comment by gergelyke** [comment]
How about as soon as october?

**Comment by madbence** [comment]
Sure, fine for me!

**Comment by gergelyke** [comment]
Then it is a go :)

**Comment by EggDice** [comment]
+1

**Comment by oroce** [comment]
also please mention why it is super useful, and show us some easily understandable examples ;)

**Comment by gergelyke** [comment]
@madbence how about doing this in October?
