### ISSUE TITLE
Brewing with Node

### ISSUE THREAD

**Issue by hekike** [nodebp/nodebp#3]
How/Why we built a NodeJS powered brewing system.

Topics:
- Brewing beer
- Brewing systems (Herms, BIAB)
- My homebrew experiences
- NodeJS-MEAN powered BIAB system

I'm Peter Marton and I'm in love with Node and AngularJS :)
https://twitter.com/slashdotpeter

**Comment by oroce** [comment]
accepted.

added milestone.

**Comment by oroce** [comment]
added to the readme: [link](https://github.com/nodebp/nodebp/blob/master/2013-Nov.md#3-brewing-with-node-s%C3%B6rf%C5%91z%C3%A9s-nodejs-sel-by-peter-marton)
