### ISSUE TITLE
Nodebots

### ISSUE THREAD

**Issue by gergelyke** [nodebp/nodebp#30]
arduino with johnny-five

**Comment by EggDice** [comment]
:+1:
arduino with jony ive?
![arduino with jony ive](https://cloud.githubusercontent.com/assets/2384493/4300537/da9b66be-3e45-11e4-929d-6d1815ddcd64.jpg)

**Comment by gergelyke** [comment]
@EggDice @madbence @hekike @oroce how about adding this to the October meetup as well? Would be a great intro for the nodebots workshop in November
