### ISSUE TITLE
Private NPM registry (sinopia + docker)

### ISSUE THREAD

**Issue by madbence** [nodebp/nodebp#36]
I've been playing with [sinopia](https://github.com/rlidwka/sinopia) and [docker](https://www.docker.com/) for a while, and I'd love to present my solution.

Main topics:
- What is docker?
- What is sinopia?
- How can set up a full-featured sinopia instance just in a few minutes?
- How can I use my private registry?

**Comment by gergelyke** [comment]
Sounds like a plan!

**Comment by oroce** [comment]
what about march?

**Comment by EggDice** [comment]
We are still short on February. It is almost one month. Or we get somebody to talk about iojs?

**Comment by gergelyke** [comment]
Would be great to have an io.js talk, yes!

On Mon, Jan 26, 2015 at 4:07 PM, Tamas Kokeny notifications@github.com
wrote:

> We are still short on February. It is almost one month. Or we get somebody
> to talk about iojs?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodebp/nodebp/issues/36#issuecomment-71474365.

## 

_Gergely Nemeth_
Phone: + 36 30 926 1231
Twitter: @nthgergo

**Comment by oroce** [comment]
if we would do this in march, we could do another talk how to use the private to share everything (I mean less, jade, js), how to include the private npm in your build workflow, etc
