### ISSUE TITLE
NodeSummit Retrospective

### ISSUE THREAD

**Issue by gergelyke** [nodebp/nodebp#38]
Happy to give a quick (5min) retro on NodeSummit in Feb cc. @judikdavid

**Comment by oroce** [comment]
what about a 10 min?:)

**Comment by gergelyke** [comment]
Sounds good :)

On Tue, Feb 10, 2015 at 10:55 AM, Róbert Oroszi notifications@github.com
wrote:

> what about a 10 min?:)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodebp/nodebp/issues/38#issuecomment-73759451.

## 

_Gergely Nemeth_
Phone: + 36 30 926 1231
Twitter: @nthgergo

**Comment by judikdavid** [comment]
Alrigthy, guys :)
