### ISSUE TITLE
Node.js at Arkon

### ISSUE THREAD

**Issue by mefiblogger** [nodebp/nodebp#41]
We are working with Node.js since October on ingatlan.com at Arkon. With my fellow colleague @maerlyn we will talk about how did we start and what do we use it for. Keywords: Express, Knex, Nodemailer, RabbitMQ, Swig.

**Comment by oroce** [comment]
wow great. 

scheduled for March.

**Comment by mefiblogger** [comment]
Hi Guys,

You can find our slides here:

https://github.com/mefiblogger/meetup/blob/master/nodebp/nodebp_20150326_nodejsatarkon.pdf

Thanks for coming, it was a very cool meetup!

Mefi
