### ISSUE TITLE
Callback vs. EventEmitter vs. Promises

### ISSUE THREAD

**Issue by gergelyke** [nodebp/nodebp#8]

**Comment by oroce** [comment]
Actually i think it shouldn't just cover the eventemitter, callback and promise thing.

I suggest you should talk about the flow control using the mentioned solutions.
- what is callback (error first, etc)
- how to use eventemitter in your klass
- what are the use cases for promises
- how to handle six or ten deep callback spaghetti code
- introduction of async (async.auto, parallel, series, eachLimit, etc)
- flow control using streams
- flow control using promises
- error bubbling in promises,in callbacks, in streams

What do you think?

**Comment by madbence** [comment]
We should mention generators (`yield`, etc), it is a much more cleaner solution to flow control, and it's available in `node`. `await` is still far away, but it's available in traceur (and other ES{6,7,...}->ES5 transpilers), and there are some node forks with working implementations.

**Comment by oroce** [comment]
@madbence +1

**Comment by oroce** [comment]
I had chat with @gergelyke and we agreed we need two presentations about this topic.

First one should introduce events, promises and callbacks.

Second one should cover the flow control tools.

**Comment by madbence** [comment]
It's a very big topic, we should start from the beginning: node event loop (reactor pattern, `libuv` abstraction layer), events, callbacks (and continuations). Then we should introduce promises, what are they, current specifications (very shortly), and at the end we should talk briefly about generators (coroutines), and why can they used for async flow control.

**Comment by gergelyke** [comment]
How about do this in January? Then we would have a beginner preso (event loop, events, callbacks, event emitter... ), and an expert preso (streams, promises, generator ..  ) as well.

**Comment by madbence** [comment]
You can count on me with this one :)

**Comment by gergelyke** [comment]
Great! Which part?

**Comment by madbence** [comment]
I'd like to talk about the second part, generators have arrived to v8 a few months ago, native Promise implementations are available in nighly browsers since last week, so these topics are quite hot right now.

**Comment by gergelyke** [comment]
Okay, with one quick note: i think we should mention also, that promises were part of the node.js core some time back, but got removed: but what i wanted to say, is the we shouldn't mix the browsers into the presentation, just mention it very briefly.

**Comment by gergelyke** [comment]
See at: https://github.com/nodebp/nodebp/blob/gh-pages/2014-Jan.md#1-async-101-by-gergely-n%C3%A9meth
and 
https://github.com/nodebp/nodebp/blob/gh-pages/2014-Jan.md#2-async-201-by-bence-danyi
